"""
FloodGuard AI - REST API Endpoints: /notifications/*
Exposes notification queries and mark-as-read endpoints.
"""
from __future__ import annotations

from typing import Any, Dict, List, Optional
from fastapi import APIRouter, Depends, Query
from fastapi.responses import JSONResponse
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.deps import get_db
from app.services.notification_service import NotificationService

router = APIRouter()


@router.get("", summary="Get system notifications")
async def get_notifications(
    notification_type: Optional[str] = Query(default=None, description="Filter by type (high_risk_prediction, verified_report, shelter_capacity_warning, critical_emergency)"),
    unread_only: bool = Query(default=False),
    db: Optional[AsyncSession] = Depends(get_db),
) -> JSONResponse:
    """
    Retrieve system notifications generated by risk predictions, verified reports,
    shelter capacity warnings, and emergency updates.
    """
    items = await NotificationService.get_notifications(
        db=db,
        notification_type=notification_type,
        unread_only=unread_only,
    )
    return JSONResponse(content={
        "total_notifications": len(items),
        "unread_count": len([i for i in items if not i.get("is_read")]),
        "notifications": items,
    })


@router.patch("/{notification_id}/read", summary="Mark notification as read")
async def mark_notification_read(
    notification_id: str,
    db: Optional[AsyncSession] = Depends(get_db),
) -> JSONResponse:
    """Mark a notification as read by ID."""
    await NotificationService.mark_as_read(db, notification_id)
    return JSONResponse(content={"status": "success", "message": f"Notification '{notification_id}' marked as read."})


@router.post("/mark-all-read", summary="Mark all notifications as read")
async def mark_all_notifications_read(
    db: Optional[AsyncSession] = Depends(get_db),
) -> JSONResponse:
    """Mark all system notifications as read."""
    await NotificationService.mark_all_read(db)
    return JSONResponse(content={"status": "success", "message": "All notifications marked as read."})
