import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from 'react-router-dom';
import { Menu, Moon, Sun } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { useState } from 'react';
import { useTheme } from '@/providers/theme-provider';
export function Header({ showSidebarToggle }) {
    const { theme, setTheme } = useTheme();
    const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
    const toggleTheme = () => setTheme(theme === 'dark' ? 'light' : 'dark');
    return (_jsxs("header", { className: "sticky top-0 z-40 w-full border-b border-slate-200 dark:border-slate-800 bg-white/80 dark:bg-slate-900/80 backdrop-blur-md", children: [_jsxs("div", { className: "flex h-16 items-center justify-between px-4 md:px-6", children: [_jsxs("div", { className: "flex items-center gap-4", children: [showSidebarToggle && (_jsx("button", { className: "md:hidden rounded-md p-2 text-slate-500 hover:bg-slate-100 dark:hover:bg-slate-800", onClick: () => setMobileMenuOpen(!mobileMenuOpen), children: _jsx(Menu, { className: "h-5 w-5" }) })), _jsxs(Link, { to: "/", className: "flex items-center gap-3", children: [_jsx("img", { src: "/logo.png", alt: "FloodGuard Logo", className: "h-8 w-auto object-contain rounded-lg border border-slate-700/50 bg-slate-900/80 p-0.5" }), _jsx("span", { className: "font-bold text-lg tracking-tight hidden sm:inline-block", children: "FloodGuard AI \uD83C\uDF0A" })] })] }), _jsx("nav", { className: "hidden md:flex items-center gap-6", children: _jsx(Link, { to: "/", className: "text-sm font-medium text-slate-600 dark:text-slate-300 hover:text-[#0D9488] transition-colors", children: "Home" }) }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx("button", { onClick: toggleTheme, className: "rounded-md p-2 text-slate-500 hover:bg-slate-100 dark:text-slate-400 dark:hover:bg-slate-800 transition-colors", "aria-label": "Toggle theme", children: theme === 'dark' ? (_jsx(Sun, { className: "h-5 w-5" })) : (_jsx(Moon, { className: "h-5 w-5" })) }), !showSidebarToggle && (_jsx("button", { className: "md:hidden rounded-md p-2 text-slate-500 hover:bg-slate-100 dark:hover:bg-slate-800", onClick: () => setMobileMenuOpen(!mobileMenuOpen), children: _jsx(Menu, { className: "h-5 w-5" }) }))] })] }), _jsx(AnimatePresence, { children: mobileMenuOpen && !showSidebarToggle && (_jsx(motion.div, { initial: { height: 0, opacity: 0 }, animate: { height: 'auto', opacity: 1 }, exit: { height: 0, opacity: 0 }, className: "md:hidden overflow-hidden border-t border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900", children: _jsx("nav", { className: "flex flex-col p-4 gap-4", children: _jsx(Link, { to: "/", className: "text-sm font-medium p-2 rounded-md hover:bg-slate-100 dark:hover:bg-slate-800", onClick: () => setMobileMenuOpen(false), children: "Home" }) }) })) })] }));
}
//# sourceMappingURL=header.js.map